In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
matrix = np.random.rand(3,3)

In [4]:
print('原始矩阵:\n',matrix)

原始矩阵:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [5]:
U,Sigma,VT = np.linalg.svd(matrix)

In [6]:
print('U矩阵:\n',U)

U矩阵:
 [[-0.75376484 -0.06431174 -0.65398973]
 [-0.22347331 -0.91080089  0.34713315]
 [-0.61797916  0.40780602  0.67215773]]


In [7]:
print('奇异值:\n',Sigma)

奇异值:
 [1.66672816 0.56866011 0.02526264]


In [8]:
print('VT矩阵:\n',VT)

VT矩阵:
 [[-0.27118629 -0.77202741 -0.57483187]
 [-0.95955238  0.26375656  0.09844645]
 [ 0.07561232  0.57827861 -0.8123279 ]]


In [9]:
Sigma_mat = np.diag(Sigma)

In [11]:
reconstructed_mat = U@Sigma_mat@VT

In [12]:
print('重构矩阵:\n',reconstructed_mat)

重构矩阵:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
